[squash] Add dependency for groovy-xml
To fix:
[ERROR] testAvailable  Time elapsed: 6.882 s  <<< ERROR!
java.lang.NoClassDefFoundError: groovy/util/slurpersupport/GPathResult
	at org.apache.dubbo.registry.consul.ConsulRegistryTest.setUp(ConsulRegistryTest.java:55)
Caused by: java.lang.ClassNotFoundException: groovy.util.slurpersupport.GPathResult
	at org.apache.dubbo.registry.consul.ConsulRegistryTest.setUp(ConsulRegistryTest.java:55)